services:
  # ========================
  # FRONTEND
  # ========================

  frontend:
    build: ./frontend-web
    container_name: gh_frontend
    ports:
      - "3000:3000"
    command: sh -c "${FRONTEND_CMD:-npm install && npm run dev}"
    volumes:
      - ./frontend-web:/app
    depends_on:
      - api

  # ========================
  # BACKEND
  # ========================

  api:
    build: ./backend
    container_name: gh_api
    ports:
      - "8000:8000"
    command: sh -c "composer install && php artisan serve --host=0.0.0.0 --port=8000 & while [ ! -f vendor/autoload.php ]; do sleep 1; done && while true; do php artisan schedule:run; sleep 60; done"
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
      - redis
      - mailpit

  queue-worker:
    build: ./backend
    container_name: gh_queue
    command: sh -c "while [ ! -f vendor/autoload.php ]; do sleep 1; done; php artisan queue:work"
    volumes:
      - ./backend:/var/www
    depends_on:
      - api
      - redis


  # ========================
  # DATABASE
  # ========================

  db:
    image: postgres:16
    container_name: gh_db
    environment:
      POSTGRES_DB: horarios
      POSTGRES_USER: horarios
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ========================
  # REDIS
  # ========================

  redis:
    image: redis:7-alpine
    container_name: gh_redis
    ports:
      - "6379:6379"

  # ========================
  # MAILPIT
  # ========================

  mailpit:
    image: axllent/mailpit:latest
    container_name: gh_mailpit
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

volumes:
  postgres_data:
